version: '3.1'

services:
  web:
    build: .
    command: 'yarn start'
    env_file: .env
    ports:
      - '3000:3000'
      - '1222:1222'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: 'postgres:10.3'
    volumes:
      - tokentax-db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  tokentax-db-volume:
    driver: local
