version: '3.1'

services:
  web:
    build: .
    command: 'yarn start'
    # env_file: .env
    ports:
      - '3000:3000'
      - '1222:1222'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db  
  db:
    image: 'postgres:10.3'
    volumes:
      # - tokentax-db-volume:/var/lib/postgresql/data
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d

    ports:
      - '5432:5432'
    environment:
      - POSTGRES_MULTIPLE_DATABASES="tt_history_dev","tt_history_test"
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=password  
# volumes:
#   tokentax-db-volume:
#     driver: local

