apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrape-live
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tt-pricing
            image: gcr.io/tokentax-infra-209601/tt-pricing:latest
            imagePullPolicy: Always
            command: ["node", "./build/scraper.js"]
            env:
            - name: PRICE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pricing-db-url
                  key: PRICE_DATABASE_URL
          restartPolicy: Never
  